# Generated by Django 3.2.4 on 2021-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=70)),
                ('option_two', models.CharField(max_length=70)),
                ('option_three', models.CharField(max_length=70)),
                ('option_four', models.CharField(max_length=70)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
