# Generated by Django 3.2.4 on 2021-07-10 05:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='uservote',
            field=django_mysql.models.ListCharField(models.CharField(max_length=30), default='', max_length=2200, size=20),
            preserve_default=False,
        ),
    ]
