# Generated by Django 3.2.4 on 2021-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('ifsc', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(max_length=20)),
            ],
        ),
    ]
